apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: multibucket
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/nstogner/composing-infra-with-k8s
  ref:
    branch: main
