apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: abc
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: helmplane/multibucket
      version: '0.2.0'
      sourceRef:
        kind: GitRepository
        name: multibucket
        namespace: flux-system
      interval: 1m
  values:
    bucketPrefix: aljkdfslgghhha
    bucketRegion: us-east-1
    names:
    - abc
    - xyz
