apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: multibuckets.example.com
spec:
  group: example.com
  scope: Cluster
  names:
    plural: multibuckets
    singular: multibucket
    kind: MultiBucket
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                names:
                  type: array
                  items:
                    type: string
            status:
              type: object
              properties:
                ready:
                  type: boolean
      subresources:
        status: {}
